# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0c1e29d32b1190eddf7abad5fcaaa1d00884f80334ea3bb92f771666c95a594ea7aa188dea68cbc68a144439515e458178cf38ddd77014a2595a61a621a0b02

test:
  secret_key_base: 85871c7c8f8284da2ef52cdbd3ed26bb84b43c33e85e7cf579fc922e11032f287105c09e4001125d5b81b2c6316f08e3efad004ba7a43221c5b156aaaf8c08e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
